### ISSUE TITLE
Use fast-json-stringify or slow-json-stringify instead

### ISSUE THREAD

**Issue by NightyLighty** [nguyenphuminh/JeChain#2]
Using [fast-json-stringify](https://github.com/fastify/fast-json-stringify) or [slow-json-stringify](https://github.com/lucagez/slow-json-stringify/blob/master/benchmark.md) will probably improve the performance.
*Maybe not so much impact on performance, but it's worth a try.*

**Comment by nguyenphuminh** [comment]
JeChain is kind of a prototype currently, so I don't really dig too deep into performance (and I might switch to another language in the future), so I think the normal `JSON.stringify` would get the job done for now.

Thanks for the suggestion, I really appreciate it!
