### ISSUE TITLE
Public Chain

### ISSUE THREAD

**Issue by simonegosetto** [nguyenphuminh/JeChain#49]
have you a public chain and / or public nodes to connect to ?

**Comment by nguyenphuminh** [comment]
Sadly no, there are still tons of work to do, bugs to fix and weird stuff (like the current state transition model and contract execution environment for example).

Also I haven't thought of *actually* running it publicly, currently it's just a fun experimental project that I sometimes update in my free time, and people can use its codebase to kind of learn how blockchains work and maybe roll out their own toy chains.
