### ISSUE TITLE
Suggestion: Its about time that the functions/classes are split into their own files/directories

### ISSUE THREAD

**Issue by glaukiol1** [nguyenphuminh/JeChain#5]
**Is your feature request related to a problem? Please describe.**
This might be a problem in the future, since the project is always expanding, the code is getting less and less readable.

**Describe the solution you'd like**
You could split the functions/classes in separate files/directories. Seeing your project has made me go back to building blockchains, since I made a blockchain in JavaScript a long time ago. Im now working on [gagchain](https://github.com/glaukiol1/gagchain), its a blockchain thats built in Go, and I have split the files into directories and it just makes the overall code neater. I have also read your blogs on blockchains, even though im building it in Go rather than JavaScript. Actually, in my `blockchain/block.go` file, I have linked your dev.to blog on minting and gas fees, as you can see [here](https://github.com/glaukiol1/gagchain/blob/main/blockchain/block.go). I have also written my own way of communicating nodes in TCP, although its not done yet. I have also look at your project for this, like the `TYPE_GET_TESTTEST` messages.

**Additional context**
It would be better for everyone to make the code more readable! Please consider this.

Thanks!

**Comment by nguyenphuminh** [comment]
Thanks for your suggestion, I absolutely agree with you on writing clean codes for scalability of the project, I will update the code soon.

**Comment by nguyenphuminh** [comment]
@glaukiol1 Check out v0.5.0: https://github.com/nguyenphuminh/JeChain/releases/tag/v0.5.0. This is only my first step on re-structuring the code though, there are still a lot to change.

**Comment by glaukiol1** [comment]
Thanks for the changes! This will definitely help the project as it scales, and for people like me, it would be easier to understand whats going on. Thank you!
