### ISSUE TITLE
Effective mining to save blocks

### ISSUE THREAD

**Issue by simonegosetto** [nguyenphuminh/JeChain#53]
I really like this project and I am studying it, I also try to think about some basic use cases.

I think a parameter could be useful to mine only when transactions from outside (RCP) are pushed, there are many chain that use this approach, what do you think?

obviously I would like to make it myself

**Comment by godwnwaswa** [comment]
hey, it's cool that you're also studying this project, how are you spinning up the nodes and simulating how the an actual blockchain could work?

**Comment by godwnwaswa** [comment]
wow! i want to use is as the underlying infrastructure in my Fintech startup, am using laravel and it's support for websockets is so neat, am thinking of implementing this same network in laravel, w/d/y/t?

**Comment by simonegosetto** [comment]
in my Agency i'm using nodejs on back-end side but i would be great to have a chain cross-language !
ps. i've sent to you a PR :)

**Comment by godwnwaswa** [comment]
nodejs is super slim and magical, it's worthwhile for a minimalistic implementation of a feature inside another framework, which other langs are u good at.

# no pr yet, this is my fork: [https://github.com/godwnwaswa/DrissNetwork](DrissNetwork)

**Comment by simonegosetto** [comment]
done ! i'm also working on your project for compile it with webpack with the goal of produce a single file to run with node
