### ISSUE TITLE
NAT problem p2p

### ISSUE THREAD

**Issue by GemsGame** [nguyenphuminh/JeChain#86]
Hello! How did you resolve a NAT problem in your project?

**Comment by nguyenphuminh** [comment]
Can you elaborate? There are many problems regarding NAT.

**Comment by GemsGame** [comment]
I mean do you have a peer connection system between peers if the people are behind NAT?  The peers (mining nodes) will be work in one Network but if they have different networks they don't

**Comment by nguyenphuminh** [comment]
As JeChain is still experimental, users must port forward to communicate with public nodes. In the future, I will add in several options like upnp or relays.
